#!/usr/bin/env bash

output=$(python3 ../imc-prosperity-3-backtester-master/prosperity3bt/__main__.py auto.py 1-0)
fname=$(echo "$output" | tail -n 1 | cut -d' ' -f6)
bname=$(basename "$fname" | cut -d'.' -f1)
echo "$output"
echo "" 
echo "Saved logs and script to backtests/$bname"

mkdir backtests/"$bname"
mv "$fname" backtests/"$bname"
cp auto.py backtests/"$bname"


